"""Regenerate the known-divergence baseline for the fast-path differential.

Records every corpus case that currently disagrees with the pinned
jsonata-js, so the harness can run green and fail on *new* divergences.
Shrinking this file is the point; run this after fixing one.

Usage: uv run python scripts/gen_fastpath_baseline.py
"""

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / "tests" / "python"))

import test_fastpath_differential as harness  # noqa: E402

import jsonatapy  # noqa: E402

DEST = pathlib.Path(__file__).parent.parent / "tests" / "fixtures" / "fastpath_known_divergences.json"


def main():
    divergences = {}
    engine_specific = 0
    for case in harness.CASES:
        found = {}
        for forced in (False, True):
            jsonatapy._set_force_tree_walker(forced)
            for entry in harness.ENTRIES:
                detail = harness.diverges(case, entry)
                if detail:
                    found[(forced, entry)] = detail
        jsonatapy._set_force_tree_walker(False)
        if 0 < len(found) < 2 * len(harness.ENTRIES):
            engine_specific += 1
        for (forced, entry), detail in found.items():
            divergences["|".join(harness.case_key(case, forced, entry))] = detail

    DEST.write_text(
        json.dumps(
            {
                "_comment": (
                    "GENERATED by scripts/gen_fastpath_baseline.py. Pre-existing divergences "
                    "from the pinned jsonata-js, marked xfail(strict) by "
                    "tests/python/test_fastpath_differential.py. Shrink this list; do not grow it."
                ),
                "reference": harness._corpus["reference"],
                "divergences": divergences,
            },
            indent=2,
        )
        + "\n"
    )
    combos = 2 * len(harness.ENTRIES)
    print(f"wrote {len(divergences)} known divergences over {len(harness.CASES)} cases x {combos} routes")
    print(f"  {engine_specific} diverge on some routes but not others")
    print("  (an optimisation disagreeing with the path it replaces, not a shared gap)")
    print(f"  -> {DEST}")


if __name__ == "__main__":
    main()
